### ISSUE TITLE
Shiny app-plot save

### ISSUE THREAD

**Issue by sridhar0605** [ialbert/genescape-central#15]
When I use dummy gene list below with default params (All roots) Having a hard time saving the plot, Am i missing something?

I tried setting BP, MF, CC roots individually too, hoping that this would reduce plotting space but that did not seem to help. 
```
COPS3
DEK
DIAPH3
EPSTI1
EXOSC1
FANCA
FKBP1A
GALT
GALT
HACL1
ING4
KIAA1586
LY96
MARS
MARS
METTL15
PIK3CB
PPIL3
PRC1
RAB34
RABGEF1
RSRC2
SNHG5
SNUPN
SUGP2
SUGP2
TAF1D
TARBP2
TMEM11
U2AF1L4
ZNHIT1
ZSWIM8
ABHD14B
ABHD14B
ABI1
AC006254.1
AC104452.1
ACAP1
ADAM15
ADD3
AHCTF1
ALCAM
ALDH16A1
ALG2
ANKHD1-EIF4EBP3
ANKRD11
ANKRD17
ANXA11
AP1G1
APPL2
APTX
APTX
ARHGAP23
ARID1B
ARNT
ATF2
ATF2
ATF4
ATG16L2
ATP2C1
ATP2C1
ATP2C1
ATP5MD
ATP6V1A
ATRIP
ATRX
ATXN2L
BAZ1A
BAZ2B
CARD8
CARD8
CASC4
CBWD1
CCDC88A
CCND3
CCNL2
CCNL2
CD37
CD46
CDIPT
CENPT
CENPT
CFAP410
CHKA
CIRBP
CLEC12A
CLK3
CLK3
CNEP1R1
COMMD2
```

**Comment by ialbert** [comment]
This is a problem with graphviz library most likely, the resulting graph is too big for it to generate a PNG out of it. I believe that it is the graphviz library has trouble dealing rendering an overly large graph, 

Set the mincount to 2 instead of 1 and you will get an output but it is 13MB image, 

The mincount is the parameter that has the strongest effect. The mincount represents the minimum number of genes share that function. Usually filtering above 1 reduces the graph size.

Thus, it is not the number of genes one includes but the threshold via the mincount that determines the limitations relative to a gene list.

Maybe I could call that parameter something else, that better indicates what it does.

I'll add a clear note in the README about the effect of `mincount`

**Comment by ialbert** [comment]
This is not fixable in the sense that it is a limitation of the graph rendering engine, 

there is no limit on the number of genes that can be annotated for example, large lists can also be reduced in size

but depending on which front end one uses the engine may not be able to draw a PNG when it can still make an SVG for example. 

in version 0.9.4., the main web interface has documentation that talks about reducing graph sizes.
